# arxivの学問領域の指定
subject: 'astro-ph'
keywords:
        circumplanetary disk: 1
        protostellar: 1
        protostar: 1
        protoplanetary: 1
        protoplanetary disk: 1
        protoplanetary disc: 1
        circumstellar disk: 1
        circumstellar disc: 1
        protoplanet: 1
        pre-main sequence: 1
        debris disk: 1
        debris disc: 1
        T Tauri: 1
        transition disk: 1
        transition disc: 1
        planet formation: 1
        planetary formation: 1
        radio interferometry: 1
        sparse modeling: 1
        regularized maximum likelihood: 1
        protostar: 1
        SETI: 1
        Herbig Ae: 1
        Herbig Ae/Be: 1
        photo-evaporation: 1
        snowline: 1
        UX Ori type: 1
        FU Ori: 1
        young star: 1
        Regularized  Maximum  Likelihood: 1
        dust trapping: 1
        pebble accretion: 1
# 通知の閾値
score_threshold: 0
